# Generated by Django 5.2.2 on 2025-06-05 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('YOGA', 'Yoga'), ('ZUMBA', 'Zumba'), ('HIIT', 'HIIT'), ('GYM', 'Gym'), ('CARDIO', 'Cardio')], max_length=100, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('booked_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fitness Class',
                'verbose_name_plural': 'Fitness Classes',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('WAITLIST', 'Waitlist')], default='CONFIRMED', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.fitnessclass')),
            ],
        ),
    ]
